# Prefix を Ctrl-a に変更し、Ctrl-b はシェル側で使えるようにする
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# prefix + q で表示される pane 番号を少し長めに表示する
set-option -g display-panes-time 2000

# pane の分割キーを設定する
bind-key \\ split-window -h -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# コピーモードを Vim ライクな操作にする
set-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection

# ESC の反応を速くする
set-option -s escape-time 0

# マウス操作とスクロールを有効にする
set-option -g mouse on
bind-key -T copy-mode-vi WheelUpPane send-keys -X scroll-up
bind-key -T copy-mode-vi WheelDownPane send-keys -X scroll-down
