add_newline = true

format = """
$directory  \
$git_branch\
$docker_context\
$kubernetes\
$terraform\
$direnv\
$fill\
$cmd_duration\
$time\
\n$character\
"""

# Enable if it appears on the same line as the command
# right_format = """
# $cmd_duration\
# $time\
# """

[python]
format = """
[](fg:#0f6f9c)\
[ $virtualenv ]($style)\
[](fg:#0f6f9c)\
"""
style = "bold fg:#eaf7ff bg:#0f6f9c"

[fill]
symbol = "─"

[directory]
truncation_length = 6
truncation_symbol = " "
truncate_to_repo = false
home_symbol = "~"
read_only = " 󰌾 "
format = """
[](fg:#0e6a96)\
[ $path ]($style)\
[$read_only]($read_only_style)\
[](fg:#0e6a96)\
"""
style = "bold fg:#eef8ff bg:#0e6a96"
read_only_style = "bold fg:#eef8ff bg:#0e6a96"

[direnv]
disabled = false
format = """
[](fg:#1379a7)\
[ $symbol$allowed ]($style)\
[](fg:#1379a7)\
"""
style = "bold fg:#eef8ff bg:#1379a7"

[git_branch]
symbol = ""
style = "bold fg:#eef8ff bg:#117eaF"
format = """
[](fg:#117eaf)\
[ $symbol $branch ]($style)\
[](fg:#117eaf)\
"""

[docker_context]
only_with_files = true
detect_files = ["Dockerfile", "docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml"]
symbol = ""
style = "bold fg:#eef8ff bg:#106f9d"
format = """
[](fg:#106f9d)\
[ $symbol $context ]($style)\
[](fg:#106f9d)\
"""

[kubernetes]
disabled = false
symbol = "☸"
detect_files = ["k8s.yaml", "k8s.yml", "kustomization.yaml", "kustomization.yml", "Chart.yaml", "helmfile.yaml", "helmfile.yml"]
detect_folders = ["k8s", "kubernetes", "helm", "charts"]
style = "bold fg:#eef8ff bg:#1177a4"
format = """
[](fg:#1177a4)\
[ $symbol $context( \\($namespace\\)) ]($style)\
[](fg:#1177a4)\
"""

[terraform]
symbol = "󱁢"
detect_extensions = ["tf", "tfplan", "tfstate"]
detect_files = [".terraform.lock.hcl"]
detect_folders = [".terraform"]
style = "bold fg:#eef8ff bg:#0d678f"
format = """
[](fg:#0d678f)\
[ $symbol $workspace ]($style)\
[](fg:#0d678f)\
"""

[git_status]
style = "fg:#769ff0 bg:#1d2230"
format = """
[$all_status$ahead_behind]($style)\
[](fg:#1d2230)\
"""

[cmd_duration]
min_time = 1
style = "bold fg:#e3f6ff bg:#085780"
format = """
[](fg:#085780)\
[ $duration ]($style)\
[](fg:#085780)\
"""

[time]
disabled = false
time_format = "%R"
style = "bold fg:#e6f7ff bg:#074766"
format = """
[](fg:#074766)\
[  $time ]($style)\
[](fg:#074766)\
"""

[character]
vimcmd_symbol = "[V](bold green) "

# [aws]
# format = "[$symbol $profile ]($style)"
# symbol = "💭"
# style = "bold fg:#ffcb6b"

# [gcloud]
# disabled = true

# [custom.gcloud]
# when = "command -v gcloud && command -v terraform"
# command = """
# f=~/.config/gcloud/configurations/config_$(cat ~/.config/gcloud/active_config 2>/dev/null || echo default)
# a=$(perl -ne 'print $1 if /^account\\s*=\\s*[^@]*@(.+)/' "$f" 2>/dev/null)
# p=$(perl -ne 'print $1 if /^project\\s*=\\s*(.+)/' "$f" 2>/dev/null)
# [ -n "$a" ] && echo "☁️ ${a}(${p})"
# """
# format = "[$output]($style)"
# style = "bold fg:#4285F4"
